### ISSUE TITLE
Scaling OpenShift app

### ISSUE THREAD

**Issue by domcleal** [theforeman/redmine#4]
Converting this to a scaling OpenShift app may give better performance as it'd separate the database and web gears, and under heavy load (six simultaneous requests IIRC) would scale up the web gears.
- [ ] Attachment storage needs to be available to all web gears
  - [Rackspace Cloud storage plugin](https://bitbucket.org/nathan_aschbacher/redmine-cloud-conveyor/wiki/Home) is outdated, designed for Redmine 2.x and old Rails version.  Maybe we could port it.
  - S3 plugin appears up to date, but we'd need an S3 account (and funding).  It also fragments our infrastructure even more.
  - No shared storage that I'm aware of on OpenShift.
  - It doesn't appear possible to use the shared database for attachment storage.
- [ ] Git repo cron jobs need disabling on all except one web cartridge
- [x] Shared secret token across web cartridges
- [ ] Is a shared Rails cache required?

**Comment by mmoll** [comment]
won't happen ;)
